[package]
name = "zed-fmt"
version = "0.1.0"
edition = "2021"
description = "Code formatter for the Zed programming language"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
colored = "2.0"
walkdir = "2.5.0"
